robot: g1

model_config_file:
  src/legged_base/config/g1_29dof-config.yaml

log_path:
  plot/data/

ll_dt: 0.002
use_sim_timer: false

kp: [
  40.2, 99.1, 40.2, 99.1, 28.5, 28.5, 
  40.2, 99.1, 40.2, 99.1, 28.5, 28.5, 
  40.2, 28.5, 28.5,
  14.3, 14.3, 14.3, 14.3, 14.3, 16.8, 16.8, 
  14.3, 14.3, 14.3, 14.3, 14.3, 16.8, 16.8
]
kd: [
  2.6, 6.3, 2.6, 6.3, 1.8, 1.8, 
  2.6, 6.3, 2.6, 6.3, 1.8, 1.8, 
  2.6, 1.8, 1.8,
  0.9, 0.9, 0.9, 0.9, 0.9, 1.1, 1.1, 
  0.9, 0.9, 0.9, 0.9, 0.9, 1.1, 1.1
]

FixStand:
  q: [ 
    -0.1, 0,0,0.3,-0.2,0,
    -0.1, 0,0,0.3,-0.2,0,
    0,0,0,
    0.35, 0.18,0,0.87,0,0,0,
    0.35,-0.18,0,0.87,0,0,0
  ]

PreIDLE:
  q: [
    -0.1,0,0,0.3,-0.2,0, 
    -0.1,0,0,0.3,-0.2,0,  
    0,0,0,  
    0.35,0.18,0,0.87,0,0,0, 
    0.35,-0.18,0,0.87,0,0,0
  ]