model_config_file:
  src/legged_base/config/go2-config.yaml
log_path:
  plot/data/

ll_dt: 0.002
use_sim_timer: false

PdStand:
  kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
  kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
  q_liedown: [-0.35, 1.36, -2.65, 0.35, 1.36, -2.65, -0.5,  1.36, -2.65, 0.5,  1.36, -2.65]
  q_stand: [0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5]
  x_max: 0.05
  y_max: 0.05
  z_min: 0.15
  z_max: 0.389
  roll_max: 0.85
  pitch_min: -0.59
  pitch_max: 0.45
  yaw_max: 0.6    # 1.0
