robot: go2

model_config_file:
  src/legged_base/config/go2-config.yaml
log_path:
  plot/data/

ll_dt: 0.002
use_sim_timer: false

kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]

FixStand:
  q: [0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 0.8, -1.5]

PreIDLE:
  q: [-0.35, 1.36, -2.65, 0.35, 1.36, -2.65, -0.5,  1.36, -2.65, 0.5,  1.36, -2.65]
